### Crear un Room
POST http://chelenko-data.sa-east-1.elasticbeanstalk.com/api/rooms
Content-Type: application/json

{
    "roomNumber": "102",
    "type": "DOUBLE",
    "basePrice": 150.00,
    "capacity": 3,
    "amenities": ["Wi-Fi", "Televisión", "Minibar"],
    "status": "AVAILABLE",
    "description": "Habitación doble con vistas al mar",
    "images": ["url_imagen_1", "url_imagen_2"]
}

### Crear un Guest
POST http://chelenko-data.sa-east-1.elasticbeanstalk.com/api/guests
Content-Type: application/json
 
{
    "firstName": "Pepito",
    "lastName": "Pepón",
    "email": "pepito@pepon.com"
}

### Crear un Reservation
POST http://chelenko-data.sa-east-1.elasticbeanstalk.com/api/reservations
Content-Type: application/json

{
  "bookingReference": "BR-123456",
  "guest": "671a84b4e480c49046885131",  
  "room": "6719b396351799080d1486c7",  
  "checkIn": "2024-11-01T14:00:00Z",
  "checkOut": "2024-11-05T12:00:00Z",
  "status": "CONFIRMED", 
  "totalPrice": 500.00,
  "channel": "DIRECT", 
  "specialRequests": "Cama adicional"
}

### crear un inventory
POST http://chelenko-data.sa-east-1.elasticbeanstalk.com/api/inventory
Content-Type: application/json

{
  "room": "6719b396351799080d1486c7",
  "date": "2024-10-24",
  "availableUnits": "5",
  "price": "120.00",
  "channel": "ALL"
}

### Crear un Rate Modification
POST http://chelenko-data.sa-east-1.elasticbeanstalk.com/api/rate-modifications
Content-Type: application/json

{
  "room": "671a8128ad7c03e8c9be7278",
  "startDate": "2024-11-01",
  "endDate": "2024-11-10",
  "modificationType": "PRICE_CHANGE",
  "value": 1000,
  "channel": "BOOKING"
}